module.exports = {
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    RESPONSE_LOGIN: 'RESPONSE_LOGIN',
    REQUEST_SIGNUP: 'REQUEST_SIGNUP',
    RESPONSE_SIGNUP: 'RESPONSE_SIGNUP',
    REQUEST_VERIFY_EMAIL: 'REQUEST_VERIFY_EMAIL',
    RESPONSE_VERIFY_EMAIL: 'RESPONSE_VERIFY_EMAIL',
    
    COMUNITY_CHAT: 'COMUNITY_CHAT',
    USER_CONNECTED: 'USER_CONNECTED',
    MESSAGE_RECIEVED: 'MESSAGE_RECIEVED',
    MESSAGE_SENT: 'MESSAGE_SENT',
    USER_DISCONNECTED: 'USER_DISCONNECTED',
    TYPING: 'TYPING',
    VERIFY_USER: 'VERIFY_USER',
    LOG_OUT: 'LOG_OUT'
}