module.exports = {
    REQUEST_LOGIN: 'REQUEST_LOGIN',
    RESPONSE_LOGIN: 'RESPONSE_LOGIN',
    REQUEST_SIGNUP: 'REQUEST_SIGNUP',
    RESPONSE_SIGNUP: 'RESPONSE_SIGNUP',
    REQUEST_DISCONNECT: 'REQUEST_DISCONNECT',
    REQUEST_VERIFY_EMAIL: 'REQUEST_VERIFY_EMAIL',
    RESPONSE_VERIFY_EMAIL: 'RESPONSE_VERIFY_EMAIL',
    REQUEST_PRIVATE_CHAT: 'REQUEST_PRIVATE_CHAT',
    RESPONSE_PRIVATE_CHAT: 'RESPONSE_PRIVATE_CHAT',
    REQUEST_CREATE_GROUP_CHAT: 'REQUEST_CREATE_GROUP_CHAT',
    RESPONSE_CREATE_GROUP_CHAT: 'RESPONSE_CREATE_GROUP_CHAT',
    
}